version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v4-fpm
    environment:
      PHP_INI_PHAR__READONLY: "Off"
      TYPO3_VERSION: ${TYPO3_VERSION:-^10.4}
      TYPO3_ORG_PASSWORD:
      TYPO3_ORG_USERNAME:
      TRAVIS_TAG:
      typo3DatabaseHost: mysql
      typo3DatabasePassword: root
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4']
    environment:
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql
